global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'node_api'
    static_configs:
      - targets: ['node-api:3000']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']